# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c958a4c8b7949b9616234770d8d596ce26f86444e7d8c51595d1863036dc4c59fde91e10861cbd54c94e84d7caaaa81c424937a96588179c251099223f4c206f

test:
  secret_key_base: dd7072d50a2482b78163858c7cad8bb2c96cfa636aa30302291ad24df66c10ea9313f99b3395ccc69fc5673f78b33bb85b8cd0fa5f327cfae8cf81ccef766ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
